### PR TITLE
Edit Liveries.

### PR DESCRIPTION
**Pull request by rx4**
Some things I added are not necessary so it would be nice if you look at what I added and remove those unnecessary things.

### CODE REVIEW

**Comment by rx4** [comment]
Now I am going beyond liveries though.

**Comment by legoboyvdlp** [comment]
Thanks! Sorry - missed this. Is there any more changes coming or shall I merge this?

**Comment by rx4** [comment]
I need to make sure that there is not a checkbox that says stairs. It should say 'Enable L1 stairway and L2 and L3.

**Comment by rx4** [comment]
I think you can merge this now. Sorry, I accidentally added a Services/stairs folder and It should be in Models/Ground/Services/Stairs I think you should remove the folder that is Services/stairs.

**Pull request merged**
